import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dummy Setup",
  description: "Generated by create next app",
  icons: {
    icon: "https://a.storyblok.com/f/327902/1852x1846/2046f13bd2/droplet-poster.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
